FROM python:3.11.7

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY ./mocks/stablehorde /code/app

EXPOSE 5000

CMD ["uvicorn", "app.mock_stablehorde:app", "--host", "0.0.0.0", "--port", "5000"]